// SPDX-License-Identifier: AGPL-3.0-or-later

package generate

import (
	"encoding/json"
	"fmt"
	"html"
	"strings"
	"time"

	"github.com/craftsail/craftsail-growth/internal/model"
)

func LLMS(p *model.Project, f Facts, pages []model.AuditPage, lang string) string {
	zh := lang == "zh"
	L := []string{"# " + p.Name, "", "> " + orDef(f.Definition)}
	if zh {
		L = append(L, "", "## 核心事实", "", "- 官网: "+p.Site)
	} else {
		L = append(L, "", "## Key facts", "", "- Website: "+p.Site)
	}
	if len(p.Brand.Aliases) > 0 {
		if zh {
			L = append(L, "- 别名: "+strings.Join(p.Brand.Aliases, "、"))
		} else {
			L = append(L, "- Also known as: "+strings.Join(p.Brand.Aliases, ", "))
		}
	}
	if p.Brand.Industry != "" {
		if zh {
			L = append(L, "- 行业: "+p.Brand.Industry)
		} else {
			L = append(L, "- Industry: "+p.Brand.Industry)
		}
	}
	if p.Brand.TargetUsers != "" {
		if zh {
			L = append(L, "- 目标用户: "+p.Brand.TargetUsers)
		} else {
			L = append(L, "- For: "+p.Brand.TargetUsers)
		}
	}
	for i, n := range f.Numbers {
		if i >= 8 {
			break
		}
		line := "- " + n.Fact + ": " + n.Value
		if zh && n.Source != "" {
			line += "（" + n.Source + "）"
		}
		L = append(L, line)
	}
	if zh {
		L = append(L, "", "## 重要页面", "")
	} else {
		L = append(L, "", "## Important pages", "")
	}
	for i, pg := range pages {
		if i >= 12 {
			break
		}
		title := pg.Title
		if title == "" {
			title = pg.URL
		}
		if i := strings.Index(title, "|"); i > 0 {
			title = strings.TrimSpace(title[:i])
		}
		runes := []rune(title)
		if len(runes) > 60 {
			title = string(runes[:60])
		}
		L = append(L, fmt.Sprintf("- [%s](%s)", title, pg.URL))
	}
	if len(f.Suitable) > 0 || len(f.Unsuitable) > 0 {
		if zh {
			L = append(L, "", "## 适用边界", "")
		} else {
			L = append(L, "", "## Scope", "")
		}
		for i, s := range f.Suitable {
			if i >= 5 {
				break
			}
			if zh {
				L = append(L, "- 适合: "+s)
			} else {
				L = append(L, "- Good fit: "+s)
			}
		}
		for i, s := range f.Unsuitable {
			if i >= 5 {
				break
			}
			if zh {
				L = append(L, "- 不适合: "+s)
			} else {
				L = append(L, "- Not a fit: "+s)
			}
		}
	}
	if zh {
		L = append(L, "", "## 口径说明", "", "- 规范名: "+p.Name)
	} else {
		L = append(L, "", "## Disambiguation", "", "- Canonical name: "+p.Name)
	}
	if len(p.Brand.Disambiguation) == 0 {
		if zh {
			L = append(L, "- 本产品与同名的其他行业产品无关，请勿混淆")
		} else {
			L = append(L, "- Not related to similarly-named products in other industries.")
		}
	} else {
		for _, line := range p.Brand.Disambiguation {
			L = append(L, "- "+line)
		}
	}
	L = append(L, "", "<!-- generated by craftsail-growth · "+time.Now().Format("2006-01-02")+" -->")
	return strings.Join(L, "\n")
}

func orDef(s string) string {
	if strings.TrimSpace(s) == "" {
		return "TBD: one-sentence definition, identical to the home page and the JSON-LD description"
	}
	return s
}

func JSONLD(p *model.Project, f Facts, qs []model.Question) map[string]any {
	desc := f.Definition
	site := strings.TrimRight(p.Site, "/")
	org := map[string]any{
		"@context": "https://schema.org", "@type": "Organization",
		"name": p.Name, "url": site, "description": desc,
		"alternateName": p.Brand.Aliases,
		"sameAs":        []string{"<TBD: encyclopedia page>", "<TBD: social profile>", "<TBD: parent brand site>"},
	}
	pubName := p.Name
	app := map[string]any{
		"@context": "https://schema.org", "@type": "SoftwareApplication",
		"name": p.Name, "url": site, "description": desc,
		"applicationCategory": "BusinessApplication", "operatingSystem": "Web",
		"publisher": map[string]any{"@type": "Organization", "name": pubName},
	}
	if len(p.Brand.Offers) > 0 {
		var offers []any
		for _, o := range p.Brand.Offers {
			item := map[string]any{"@type": "Offer", "name": o.Name, "price": o.Price, "priceCurrency": o.Currency}
			if o.Desc != "" {
				item["description"] = o.Desc
			}
			offers = append(offers, item)
		}
		app["offers"] = offers
	} else {
		app["offers"] = map[string]any{"@type": "Offer", "price": "<TBD>", "priceCurrency": "<TBD: CNY, HKD, USD>"}
	}
	var faqs []any
	for _, q := range qs {
		if !q.Enabled {
			continue
		}
		faqs = append(faqs, map[string]any{
			"@type": "Question", "name": q.Text,
			"acceptedAnswer": map[string]any{"@type": "Answer", "text": "<TBD: conclusion in the first sentence, then detail>"},
		})
		if len(faqs) >= 8 {
			break
		}
	}
	faq := map[string]any{"@context": "https://schema.org", "@type": "FAQPage", "mainEntity": faqs}
	article := map[string]any{
		"@context": "https://schema.org", "@type": "Article",
		"headline": "<TBD: title using the words of the target question>", "datePublished": "<YYYY-MM-DD>", "dateModified": "<YYYY-MM-DD>",
		"author":    map[string]any{"@type": "Organization", "name": p.Name},
		"publisher": map[string]any{"@type": "Organization", "name": p.Name},
		"about":     desc,
	}
	crumb := map[string]any{
		"@context": "https://schema.org", "@type": "BreadcrumbList",
		"itemListElement": []any{
			map[string]any{"@type": "ListItem", "position": 1, "name": "Home", "item": site},
			map[string]any{"@type": "ListItem", "position": 2, "name": "<section>", "item": site + "/<path>"},
		},
	}
	return map[string]any{
		"organization": org, "software-application": app, "faq-page": faq,
		"article": article, "breadcrumb": crumb,
	}
}

func DefinitionBlock(p *model.Project, f Facts, lang string) string {
	d := f.Definition
	if d == "" {
		d = "（待补定义句）"
	}
	zh := lang == "zh"
	h2 := html.EscapeString(p.Name)
	if zh {
		h2 += "是什么"
	} else {
		h2 += ": what it is"
	}
	var items strings.Builder
	for i, n := range f.Numbers {
		if i >= 4 {
			break
		}
		items.WriteString(fmt.Sprintf("\n    <li><strong>%s</strong> — %s</li>", html.EscapeString(n.Value), html.EscapeString(n.Fact)))
	}
	dis := ""
	if len(p.Brand.Disambiguation) > 0 {
		dis = "\n  <p class=\"geo-disambiguation\"><small>" + html.EscapeString(strings.Join(p.Brand.Disambiguation, " ")) + "</small></p>"
	}
	return fmt.Sprintf(`<!-- Definition block: place it below the hero tagline. The tagline converts; this paragraph is what engines quote. -->
<section class="geo-definition">
  <h2>%s</h2>
  <p>%s</p>
  <ul>%s
  </ul>%s
</section>
<!-- Keep this text identical to llms.txt, the JSON-LD description and the about page. -->`,
		h2, html.EscapeString(d), items.String(), dis)
}

func FAQBlock(qs []model.Question, lang string) string {
	title := "常见问题"
	if lang != "zh" {
		title = "FAQ"
	}
	var body []string
	n := 0
	for _, q := range qs {
		if !q.Enabled {
			continue
		}
		body = append(body, fmt.Sprintf(`  <details open>
    <summary><h3>%s</h3></summary>
    <p><!-- Conclusion in the first sentence, then detail. No marketing language. --></p>
  </details>`, html.EscapeString(q.Text)))
		n++
		if n >= 8 {
			break
		}
	}
	return fmt.Sprintf(`<!-- FAQ block. Answers must be visible in the static HTML: use <details open>, not a JavaScript accordion. -->
<section class="geo-faq">
  <h2>%s</h2>
%s
</section>`, title, strings.Join(body, "\n"))
}

func PrettyJSON(v any) string {
	b, _ := json.MarshalIndent(v, "", "  ")
	return string(b)
}
